env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - jsx-a11y
rules:
  "react-hooks/rules-of-hooks": error
  "react-hooks/exhaustive-deps": warn
settings:
  react:
    version: detect
